### ISSUE TITLE
Assessment endpoint response with status 500

### ISSUE THREAD

**Issue by lautirozen** [AmericaSCORESBayArea/salesforce-data-api#150]
The assessment endpoint is showing this error: [Error: Request failed with status code 500].  The endpoint I tried
`/coach/ContactId/teamseasons/TeamSeasonId/sessions/SessionId/assessments`

**Comment by CritiqalPete** [comment]
Debug from API log:
17:11:51.888     07/11/2022     Worker-0     [MuleRuntime].uber.988: [salesforce-data-api-prod].salesforce-data-api-main.CPU_LITE @24626347     WARN
event:3adc5e50-0177-11ed-b064-06426733d504 No matching patterns for URI /coach/0031T00004GPox0QAD/teamseasons/a0q1T00000B4deJQAR/sessions/a0p1T00000PBceTQAT/assessments
17:11:51.941     07/11/2022     Worker-0     [MuleRuntime].uber.988: [salesforce-data-api-prod].salesforce-data-api-main.CPU_LITE @24626347     ERROR
event:3adc5e50-0177-11ed-b064-06426733d504 
********************************************************************************
Message               : /coach/0031T00004GPox0QAD/teamseasons/a0q1T00000B4deJQAR/sessions/a0p1T00000PBceTQAT/assessments
Element               : salesforce-data-api-main/processors/0 @ salesforce-data-api-prod:main-api.xml:13
Element DSL           : <apikit:router config-ref="salesforce-data-api-config"></apikit:router>
Error type            : APIKIT:NOT_FOUND
FlowStack             : at salesforce-data-api-main(salesforce-data-api-main/processors/0 @ salesforce-data-api-prod:main-api.xml:13)
Payload Type          : org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider
--------------------------------------------------------------------------------
Root Exception stack trace:
org.mule.module.apikit.exception.NotFoundException: /coach/0031T00004GPox0QAD/teamseasons/a0q1T00000B4deJQAR/sessions/a0p1T00000PBceTQAT/assessments
	at org.mule.module.apikit.Router.findInCache(Router.java:204)
	at org.mule.module.apikit.Router.doRoute(Router.java:158)
	at org.mule.module.apikit.Router.processEvent(Router.java:150)
	at org.mule.module.apikit.Router.processWithExtension(Router.java:138)
	at org.mule.runtime.core.internal.util.rx.RxUtils.lambda$flatMap$13(RxUtils.java:336)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:381)
	at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:490)
	at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:485)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:351)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:447)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:534)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:151)
	at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
